version: '3.7'

services:

  redis:
    image: redis:alpine
    restart: always
    ports:
     - '127.0.0.1:6379:6379'


  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_USER: fastapi
      MYSQL_PASSWORD: fastapi
      MYSQL_DATABASE: fastapi
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_INITDB_SKIP_TZINFO: 1
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - ./data/mariadb:/var/lib/mysql
